# https://yazi-rs.github.io/docs/configuration/keymap
# https://github.com/sxyazi/yazi/blob/latest/yazi-config/preset/keymap.toml

[manager]
prepend_keymap = [
	{ on   = [ "l" ], run  = "plugin --sync smart-enter", desc = "Enter the child directory, or open the file" },
]
