#! /bin/bash

#------------------------------------------------------------------------------#
								  # Monitors #
#------------------------------------------------------------------------------#

# bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

case $(monitors count) in
	1)
		bspc monitor "$(monitors primary)"   --reset-desktops F Q W E R T A S D G C V
		;;
	2)
		bspc monitor "$(monitors primary)"   --reset-desktops F A S D G
		bspc monitor "$(monitors secondary)" --reset-desktops Q W E R T C V
		;;
	3)
		bspc monitor "$(monitors primary)"   --reset-desktops F W A S D G
		bspc monitor "$(monitors left)"      --reset-desktops R C V
		bspc monitor "$(monitors right)"     --reset-desktops Q E T
		;;
esac

#------------------------------------------------------------------------------#
								  # Desktops #
#------------------------------------------------------------------------------#

for desktop_name in W C G; do
	bspc desktop $desktop_name -l monocle
done

#------------------------------------------------------------------------------#
								 # Appearance #
#------------------------------------------------------------------------------#

~/.config/bspwm/theme.sh
bspc config border_width			1
bspc config borderless_monocle		true
bspc config window_gap				16
bspc config gapless_monocle			true
bspc config split_ratio				0.52

#------------------------------------------------------------------------------#
								   # Mouse #
#------------------------------------------------------------------------------#

xsetroot -cursor_name left_ptr
bspc config focus_follows_pointer true
bspc config pointer_follows_focus true
bspc config pointer_follows_monitor true

#------------------------------------------------------------------------------#
								   # Rules #
#------------------------------------------------------------------------------#

~/.config/bspwm/rules.sh

#------------------------------------------------------------------------------#
								   # Panel #
#------------------------------------------------------------------------------#

polybarctl restart &

