#!/bin/bash

# https://github.com/junegunn/fzf/wiki/Examples#git

FZF_DEFAULT_OPTS="--ansi $FZF_DEFAULT_OPTS"
FZF_INLINE="--height=30% --reverse $FZF_DEFAULT_OPTS"

b() {
	FZF_DEFAULT_OPTS=$FZF_INLINE
	local branch
	branch=$(git branch -vv --color=always | sed -e "/^* /d" -e "s/^  //" | fzf) &&
		git switch "$(echo "$branch" | cut -d' ' -f1 )"
}
ab() {
	FZF_DEFAULT_OPTS=$FZF_INLINE
	local branch
	branch=$(git branch --all | sed -e "/^* /d" -e "s/^  //" | fzf) &&
		git switch "$(echo "$branch" | cut -d' ' -f1 )"
}
loc() {
	git ls-files -z | wc -l --files0-from=-
}
diff() {
	local files
	files=$(git diff "$@" --name-only)
	if [[ -n $files ]]; then 
		echo "$files" | fzf --preview-window="top,75%" --preview "git diff $* --color=always -- {}"
	else
		echo "No files to diff"
	fi
}
usage() {
	printf "Usage: ${0##*/} [%s]\n" "$(declare -F | cut -d" " -f3 | tr "\n" "|" | sed "s/usage|//")"
}

[[ $# -eq 0 || ! $(typeset -f "$1") ]] && { usage; exit 1; }
func=$1 && shift
$func "$@"

