#!/bin/bash

IMAGE_DIR=$HOME/.local/share/lockimages
CACHE_FILE=$HOME/.cache/lock.png

IMAGE=$(find "$IMAGE_DIR"/* -type f | shuf -n1)

[[ ! -f $IMAGE ]] && { i3lock; exit; }

convert "$IMAGE" -resize 1920x1080^ "$CACHE_FILE"
i3lock -i "$CACHE_FILE"

