#!/bin/sh

case $1 in
	active-count)
		# xrandr --current | grep -E --count " connected" ;;
		xrandr --current --listactivemonitors | head -n 1 | cut -d" " -f2 ;;
	connected)
		xrandr --current | grep -E " connected" | cut -d" " -f1 ;;
	all)
		xrandr --current | grep -E " connected" | cut -d" " -f1
		xrandr --current | grep -E " disconnected" | cut -d" " -f1
		;;
	primary)
		xrandr --current | grep -E "primary" | cut -d" " -f1 ;;
	secondary)
		xrandr --current | grep -E " connected [0-9]+" | cut -d" " -f1 ;;
	left)
		xrandr --current | grep -E " connected [0-9]+x[0-9]+\+0" | cut -d" " -f1 ;;
	right)
		# TODO: check cases when not 3 monitors
		xrandr --current | grep -E " connected [0-9]+x[0-9]+\+[1-9]" | cut -d" " -f1 ;;
	*)
		echo "Usage: monitor [count|connected|all|primary|secondary|left|right]"
esac

