#!/bin/bash

FILE_PATH=$1

[[ $# -eq 0 ]] && { echo "Usage: open filepath"; exit 1; }

FILE_EXTENSION="${FILE_PATH##*.}"
FILE_EXTENSION="${FILE_EXTENSION,,}"

case $FILE_EXTENSION in
	htm|html)
		$BROWSER "$FILE_PATH" ;;
	chm|epub|mobi)
		ebook-viewer -- "$FILE_PATH" ;;
	cbr|cbz|djvu|pdf)
		zathura -- "$FILE_PATH" ;;
	bmp|dng|gif|ico|jpg|jpeg|png|svg|tiff|webp)
		nsxiv-rifle "$FILE_PATH" > /dev/null ;;
	otf|ttf)
		gnome-font-viewer -- "$FILE_PATH" ;;
	3gp|avi|flv|m4v|mkv|mov|mp4|mpg|mpeg|ogv|qt|vob|webm|wmv)
		mpv -- "$FILE_PATH" & ;;
	flac|m4a|mp3|ogg|wav|wma)
		deadbeef "$FILE_PATH" ;;
	it|mod|s3m|xm)
		deadbeef "$FILE_PATH" ;;
	ods|xls|xlsx)
		gnumeric "$FILE_PATH" ;;
	doc|docx|odp|odt|ppt|pptx)
		libreoffice "$FILE_PATH" ;;
	gnumeric)
		gnumeric "$FILE_PATH" ;;
	jar)
		java --jar "$FILE_PATH" ;;
	# bz2|gz|tar|tgz|xz)
		# archivemount ;;
	# ssh)
		# sshfs ;;
	md5)
		md5sum -c -- "$FILE_PATH" ;;
	sha1)
		sha1sum -c -- "$FILE_PATH" ;;
	sha256)
		sha256sum -c -- "$FILE_PATH" ;;
	sha512)
		sha512sum -c -- "$FILE_PATH" ;;
	*)
		if file --dereference "$FILE_PATH" | grep -q text; then
			$TERMINAL $EDITOR "$FILE_PATH"
		else
			"$FILE_PATH"
		fi
esac

