#!/bin/bash

THIS=${0##*/}

query() {
	psql -t "$CONNECTION" -c "$1" | sed "s/|/│/g"
}

tables() {
	query "\dt" | fzf \
	--preview="$THIS $CONNECTION columns {3}" \
	--preview-window="top,75%"
}

columns() {
	query "\d+ $1"
}

usage() {
	echo "Usage: $THIS "
}

[[ $# -gt 0 ]] && CONNECTION=$1

case $# in
	1) 
		tables ;;
	3)
		$2 "$3" ;;
	*)
		usage
esac


