#!/bin/bash

THIS=${0##*/}

query() {
	psql -t "$CONNECTION" -c "$1" | sed "s/|/│/g"
}

query_data() {
	psql "$CONNECTION" -c "$1" | sed "s/|/│/g"
}

tables() {
	query "\dt"
}

columns() {
	query "\d+ $1"
}

data() {
	echo -n "$1 count: "
	query "SELECT COUNT(*) FROM $1"
	query_data "SELECT * FROM $1 LIMIT 10"
}

preview() {
	data "$1"
	columns "$1"
}

main() {
	tables | fzf 										\
	--preview="$THIS $CONNECTION preview {3}"			\
	--preview-window="top,75%"							\
	--bind "ctrl-r:reload($THIS $CONNECTION tables)"	\
	--header "Press CTRL-R to reload | ? - view data"
}

usage() {
	echo "Usage: $THIS postgresql://user@host:/database"
}

[[ $# -gt 0 ]] && CONNECTION=$1

case $# in
	0) usage	;;
	1) main		;;
	*)
		fun=$2 && shift 2
		$fun "$@"
		;;
esac

