#!/bin/bash

THIS=${0##*/}
OPTIONS="--pset=linestyle=unicode --pset=border=2"

query() {
	psql $OPTIONS "$CONNECTION" -c "$@"
}

query_tuples() {
	psql -t $OPTIONS "$CONNECTION" -c "$@"
}

tables() {
	query_tuples "\dt"
}

columns() {
	query "\d+ $1"
}

data() {
	# echo -n "$1 count: "
	# query_tuples "SELECT COUNT(*) FROM $1"
	query "SELECT * FROM $1 LIMIT 10"
}

preview() {
	columns "$1"
	data "$1"
}

main() {
	local tables=$(tables)
	[[ -z $tables ]] && exit 1
	echo $tables | fzf 										\
	--preview="$THIS $CONNECTION preview {4}"			\
	--preview-window="top,75%"							\
	--bind "ctrl-r:reload($THIS $CONNECTION tables)"	\
	--header "Press CTRL-R to reload"
}

usage() {
	echo "Usage: $THIS postgresql://user:password@host:/database"
}

[[ $# -gt 0 ]] && CONNECTION=$1

case $# in
	0) usage	;;
	1) main		;;
	*)
		fun=$2 && shift 2
		$fun "$@"
		;;
esac

