#!/bin/bash

# ╔══════════════════════════════════════════════════════════════════════════╗
# ║                                 Groups                                   ║
# ╚══════════════════════════════════════════════════════════════════════════╝

laptop() {
	desktop
	hw/bluetooth
	hw/wifi
	install xorg-xinput tlp batsignal # xinput 4 touchpad
	startenableuser batsignal
	ynstall xplugd
	sudo ln -s "$XDG_CONFIG_HOME/etc/udev/rules.d/backlight.rules" /etc/udev/rules.d/
	sudo ln -s "$XDG_CONFIG_HOME/etc/X11/xorg.conf.d/40-touchpad.conf" /etc/X11/xorg.conf.d/
}

desktop() {
	core/yay
	bspwm
	fonts
	pipewire
	terminal
	apps
}

bspwm() {
	xorg
	install bspwm sxhkd picom polybar libnotify dunst rofi rofi-calc
}

# ╔══════════════════════════════════════════════════════════════════════════╗
# ║                                 Targets                                  ║
# ╚══════════════════════════════════════════════════════════════════════════╝

# devops() {
	# install xsv rsync filezilla whois npm vscode-html-languageserver vscode-css-languageserver typescript-language-server
	# ynstall sql-language-server
# }

apps() {
	install kitty syncthing udisks2
	startenableuser syncthing.service
	install arc-gtk-theme gtk-engines gtk-engine-murrine
	install gimp gnome-font-viewer qalculate-gtk gnumeric pcmanfm	# GTK apps
	install flameshot keepassxc # Ot Apps
	install imagemagick mpv zathura-pdf-poppler
	ynstall brave-bin haiku-icon-theme
}

cron() {
	mkdir -p "$HOME"/.local/spool/anacron "$HOME"/.config/anacron/{daily,monthly,weekly}
	install cronie
	startenable cronie.service
	echo "crontab -e"
	echo '@hourly /usr/bin/anacron -s -t $HOME/.config/anacron/anacrontab -S $HOME/.local/spool/anacron'
}

core/yay() {
	pacman -Qs yay > /dev/null || (git clone https://aur.archlinux.org/yay.git /tmp/yay && cd /tmp/yay && makepkg -si)
	yay --diffmenu=false --cleanmenu=false --save
}

dev/docker() {
	install docker docker-compose
	ynstall lazydocker-bin
	startenable docker.service
	sudo groupadd docker
	sudo usermod --append --groups docker "$USER"
	echo "Relogin for adding to group to take effect" 
}
dev/go() {
	install go gopls
}
dev/nodejs() {
	install npm typescript-language-server
}
dev/php() {
	install php phpactor
}
dev/python() {
	install python python-pip pyright
}
dev/ruby() {
	ynstall asdf-vm
	asdf plugin add ruby
	asdf install ruby latest
	asdf global ruby latest
	gem install solargraph --conservative
	install yaml-language-server
}
dev/rails() {
	dev/ruby
	gem install rails --conservative
}
dev/rust() {
	install rustup rust-analyzer
	rustup default stable
}

dotfiles() {
	mkdir -p "$HOME"/.local/{bin,config,share,state} "$HOME"/.local/state/log
	# core/yay
	# TODO: git clone dotfiles
}

fonts() {
	# CJK = Chinese-Japanese-Korean
	install noto-fonts-emoji noto-fonts-cjk ttf-ubuntu-font-family ttf-ubuntu-nerd
	# ynstall nerd-fonts-victor-mono 
}

hw/bluetooth() {
	install bluez bluez-utils
	startenable bluetooth.service
	# sudo ln -s "$XDG_CONFIG_HOME/etc/udev/rules.d/bluetooth-wakeup.rules" /etc/udev/rules.d/
}
hw/nvidia() {
	install nvidia-dkms nvidia-prime
}
hw/printer() {
	install cups system-config-printer
	startenable cups.service
}
hw/printer-dcpt500w() {
	hw/printer
	install lib32-glibc		# this is needed for drivers to work, see https://aur.archlinux.org/packages/brother-dcpt500w
	ynstall brother-dcpt500w
}
hw/scanner() {
	install simple-scan sane-airscan
}
hw/redox() {
	install avr-libc avrdude
}
hw/wacom() {
	install xf86-input-wacom
}
hw/wifi() {
	install wireless-regdb
	# startenable NetworkManager.service
}

music() {
	ynstall deadbeef deadbeef-mpris2-plugin deadbeef-plugin-musical-spectrum-gtk2-git
}

nvim() {
	install neovim python python-pip python-pynvim lua-language-server ctags
	ynstall figlet-fonts 
}

pipewire() {
	install pipewire wireplumber pipewire-pulse pavucontrol playerctl
}

photo() {
	install darktable
}

terminal() {
	install fd git lsof man-db man-pages htop p7zip polkit ripgrep rsync starship
	install catdoc hexyl python-pygments mediainfo odt2txt
	install fzf lazygit smartmontools trash-cli
	install bash-language-server
	# TODO: ynstall asdf and restart terminal
	asdf plugin add shellcheck
	asdf install shellcheck latest
	asdf global schellcheck latest
	ynstall gotop nerdfetch recutils go-mtpfs wordnet-cli
	nvim
	vifm
}

vifm() {
	install vifm fuse-zip curlftpfs sshfs meld
	ynstall archivemount dragon-drop fuse3-p7zip-git
}

vm() {
	install qemu-desktop virt-manager dnsmasq
	startenable libvirtd.service
	sudo usermod --append --groups libvirt "$USER"
}

xorg() {
	install xorg-server xorg-xinit xorg-xev xdotool xclip xcolor xwallpaper arandr numlockx i3lock
	sudo ln -s "$XDG_CONFIG_HOME/etc/systemd/system/sleep@.service" /etc/systemd/system/
	sudo ln -s "$XDG_CONFIG_HOME/etc/X11/xorg.conf.d/00-keyboard-pl.conf" /etc/X11/xorg.conf.d/
	sudo ln -s "$XDG_CONFIG_HOME/etc/X11/xorg.conf.d/10-monitor.conf" /etc/X11/xorg.conf.d/
	sudo ln -s "$XDG_CONFIG_HOME/etc/X11/xorg.conf.d/50-pointer-accel.conf" /etc/X11/xorg.conf.d/
}

yazi() {
	install yazi fd ffmpegthumbnailer fzf jq ripgrep unarchiver
}

# ╔══════════════════════════════════════════════════════════════════════════╗
# ║                                  Utilz                                   ║
# ╚══════════════════════════════════════════════════════════════════════════╝

install() {
	sudo pacman -S --needed --noconfirm "$@" 
}
ynstall() {
	yay -S --needed "$@" 
}
copy() {
	sudo cp -v --no-clobber "$1" "$2"
}
startenable() {
	sudo systemctl enable "$1"
	sudo systemctl start "$1"
}
startenableuser() {
	systemctl --user enable "$1"
	systemctl --user start "$1"
}
usage() {
	local funcs
	funcs=$(declare -F | cut -d" " -f3 | grep -Ev "install|ynstall|startenable|usage" | column) # | tr "\n" ",")
	SCRIPT=${0##*/}
	cat << EOF
$SCRIPT: Install/configure packages

SYNOPSIS:
	$SCRIPT TARGET

TARGETS:
$funcs

EOF
}

# ╔══════════════════════════════════════════════════════════════════════════╗
# ║                                   Run                                    ║
# ╚══════════════════════════════════════════════════════════════════════════╝


case $# in
	0) usage; exit 2 ;;
	1) ;;
	*) echo "Too many targets $#"; exit 3 ;;
esac

[[ ! $(typeset -f "$1") ]] && { echo "Invalid target: $1"; exit 4; }
$1

