#!/bin/sh

LAYOUTS="$HOME/.local/script/screenlayout"
HOSTNAME=$(cat /etc/hostname)
CONFIG="$HOME/.config/screenlayout"

label=$(find "$LAYOUTS/$HOSTNAME"-*sh | xargs -n 1 basename | sed "s/.sh$//" | $VMENU)

file="$LAYOUTS/$label.sh"

[ -f "$file" ] || exit

"$file" || exit 1

rm "$CONFIG"
ln -s "$file" "$CONFIG"
kbrate.sh
wallpaper restore 

