#!/bin/sh

LAYOUTS="$HOME/.local/script/screenlayout"
HOSTNAME=$(cat /etc/hostname)

label=$(find "$LAYOUTS/$HOSTNAME"-*sh | xargs -n 1 basename | sed "s/.sh$//" | $VMENU)

file="$LAYOUTS$label.sh"

[ -f "$file" ] || exit

"$file" || exit 1

ln -s "$file" "$HOME/.config/screenlayout"
kbrate.sh
wallpaper restore 

