#!/bin/bash

exec >> "$HOME/.local/state/log/bashbus.log"
exec 2>&1

[[ $# -eq 0 ]] && exit 1

SIGNAL=$1 && shift
SUBSCRIBERS=$HOME/.config/bashbus

for file in "$SUBSCRIBERS/$SIGNAL"/*; do
	[[ -e $file ]] || continue
	"$file" "$@"
done

