#!/bin/bash

awk -f- /proc/cpuinfo <<'AWK'
BEGIN {
	FS=": "
	cpu_count=0
}

/^model[[:space:]]*:/       { model=$2 }
/^model name/  { name=$2 }
/^cpu cores/   { physical_cores=$2 }
/^cpu family/  { family=$2 }
/^stepping/    { stepping=$2 }
/^cache size/  { cache=$2 }
/^physical id/ { if(physical_cpus<$2)  { physical_cpus=$2 } }     \
/^processor/   { if(logical_cores<$2){ logical_cores=$2 } }   \

END {
	physical_cpus=(physical_cpus+1)
	logical_cores=(logical_cores+1)

	print "Model:",name
	print "Family/model/stepping:", family "/" model "/" stepping
	print "CPUs/Cores/Threads:",physical_cpus "/" physical_cores "/" logical_cores
	print "Cache:",cache

}
AWK

# 	/^physical id/ { if(nb_cpu<$2)  { nb_cpu=$2 } }     \
# 	/^cpu cores/   { if(nb_cores<$2){ nb_cores=$2 } }   \
# 	/^processor/   { if(nb_units<$2){ nb_units=$2 } }   \
# 	/^model name/  { model=$2 }                         \
# 	\
# 	END{                                                \
# 		nb_cpu=(nb_cpu+1);                                 \
# 		nb_units=(nb_units+1);                             \
# 		\
# 		print "CPU model:",model;                          \
# 		print nb_cpu,"CPU,",nb_cores,"physical cores per CPU, total",nb_units,"logical CPU units" \
# 	}'
