#!/bin/bash

CONFIG=${XDG_CONFIG_HOME:-$HOME/.config}
THEMES="$HOME/.local/share/themez"
CURRENT_THEME="$CONFIG/theme"
BSPWM_THEME_SCRIPT="$XDG_CONFIG_HOME"/bspwm/theme.sh

browse() {
	local file
	file=$(find "$THEMES"/*.sh -type f -printf "%f\n" | rofi -dmenu -i -p " ")
	apply "$file"
}

apply() {
	file=$THEMES/$1
	[[ -f $file ]] || { echo "Invalid file: $1"; exit 1; }

	ln -s --force "$file" "$CURRENT_THEME"
	source "$CURRENT_THEME"

	signal "theme-changed"

	# BSPWM
	[[ -x $BSPWM_THEME_SCRIPT ]] && $BSPWM_THEME_SCRIPT

	# Kitty
	envsubst < "$CONFIG/kitty/colors/template.conf" > "$CONFIG/kitty/colors/local.conf"

	# Dunst
	envsubst < "$CONFIG/dunst/dunstrc.d/colors.template" > "$CONFIG/dunst/dunstrc.d/color.conf"
	killall dunst

	# zathura
	envsubst < "$CONFIG/zathura/theme.template" > "$CONFIG/zathura/theme"
}

current() {
	if [[ -f $CURRENT_THEME ]]; then
		echo "$CURRENT_THEME"
	else
		find "$THEMES" -type f | head -n 1
	fi
}

case $1 in
	apply)    apply ;;
	current)  current ;;
	*)        browse ;;
esac

