#!/bin/bash

TODO="$HOME/Exocortex/todo.txt"

add() {
	entry="$(date +%F) $*"
	echo "$entry"  >> "$TODO"
}

case $# in
	0) ~/src/todofzf/todofzf "$TODO" ;;
	1)
		case $1 in
			edit) $EDITOR "$TODO" ;;
			*) add "$@"
		esac ;;
	*) add "$@"
esac

