#!/bin/bash

FILE=~/.cache/wallpaper
WALLPAPERS=~/Images/wallpapers
WALLSET="xwallpaper --zoom"
# WALLSET="feh --no-fehbg --bg-fill"

browse() {
	# recursive thumbnail fullscreen
	$IMGVIEWER -rtf "$WALLPAPERS" &
}

setwp() {
	[[ -f $1 ]] || { echo "Invalid file: $1"; exit ; }
	cp "$1" "$FILE"
	$WALLSET "$FILE"
}

random() {
	directory=$1
	wallpaper=$(find "$directory" -type f | shuf -n 1)
	[[ -f $wallpaper ]] && setwp "$wallpaper"
}

restorewp() {
	[[ -f "$FILE" ]] || setwp "$HOME/.local/share/wallpapers/arch_layers.png"
	$WALLSET "$FILE"
}

op=$1 && shift

case "$op" in
	"set") setwp "$@" ;;
	"restore") restorewp ;;
	"random") random "$@" ;;
	*) browse
esac

