#!/bin/bash

FILE=~/.cache/wallpaper
WALLPAPERS=~/Images/wallpapers
WALLSET="xwallpaper --zoom"
# WALLSET="feh --no-fehbg --bg-fill"

browse() {
	# recursive thumbnail fullscreen
	$IMGVIEWER -rtf "$WALLPAPERS" &
}

setwp() {
	[[ -f $1 ]] || { echo "Invalid file: $1"; exit ; }
	cp "$1" "$FILE"
	$WALLSET "$FILE"
}

restorewp() {
	[[ -f "$FILE" ]] || setwp "$HOME/.dotfiles/share/wallpapers/arch_layers.png"
	$WALLSET "$FILE"
}

case "$1" in
	"set") setwp "$2" ;;
	"restore") restorewp ;;
	*) browse
esac

