#!/bin/bash

set -e

incremental() {
	local SRC_DIR FILTER DEST_DIR BACKUP_DIR LATEST_LINK
	SRC_DIR=$(realpath "$1")
	DEST_DIR=$(realpath "$2")
	FILTER=$SRC_DIR/.backup-filter
	[[ -d $SRC_DIR ]]  || { echo "Invalid source: $SRC_DIR"; exit 1; }
	[[ -f $FILTER ]]   || { echo "Missing filter: $FILTER"; exit 2; }
	[[ -d $DEST_DIR ]] || { echo "Invalid destination: $DEST_DIR"; exit 3; }

	BACKUP_DIR=$DEST_DIR/$(date +%F_%H-%M-%S)
	LATEST_LINK=$DEST_DIR/latest

	mkdir "$BACKUP_DIR" || exit 4

	rsync                           \
		--archive                   \
		--filter="merge $FILTER"    \
		--link-dest="$LATEST_LINK"  \
		"$SRC_DIR/" "$BACKUP_DIR"  ||
		exit 3

	[[ -e $LATEST_LINK ]] && rm "$LATEST_LINK"
	ln -s --relative "$BACKUP_DIR" "$LATEST_LINK"
}

case $1 in
	incremental)
		incremental "$2" "$3" ;;
	*)
		echo "Usage: zapas incremental <src> <dest>"
esac
